version: '2'
services:
    chakanboard-app:
        image: chakanboard
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://chakanboard-mariadb:3306/chakanboard
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    chakanboard-mariadb:
        extends:
            file: mariadb.yml
            service: chakanboard-mariadb
